language: lisp

branches:
  only:
    - master

env:
  matrix:
    - LISP=sbcl
    - LISP=ecl

install:
  - curl https://raw2.github.com/luismbo/cl-travis/master/install.sh | bash

script:
  - cl-launch -i "(setf *print-pprint-dispatch* (copy-pprint-dispatch nil))(setf *readtable* (copy-readtable nil))(ql:quickload :descriptions-test)(descriptions.test:DESCRIPTIONS-TESTS)"
