language: lisp

branches:
  only:
    - master

env:
  matrix:
    - LISP=sbcl
    - LISP=ecl

install:
  - curl https://raw2.github.com/luismbo/cl-travis/master/install.sh | bash

script:
  - cl-launch -i "(ql:quickload :descriptions-test)(descriptions.test:DESCRIPTIONS-TESTS)"